version: '3.8'

networks:
  flyingdutchman_net:

services:
  flyingdutchman_db:
    image: fedec/flyingdutchman_db:latest
    container_name: flyingdutchman_db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=StrongPassword123@
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - dbdata:/var/lib/mysql
      - /srv/flyingdutchman/uploads:/srv/flyingdutchman/uploads
    networks:
      - flyingdutchman_net

  flyingdutchman:
    image: fedec/flyingdutchman:latest
    container_name: flyingdutchman
    environment:
      DB_HOST: flyingdutchman_db
    ports:
      - "8080:8080"
    depends_on:
      flyingdutchman_db:
        condition: service_healthy
    networks:
      - flyingdutchman_net

volumes:
  dbdata:
