name: FlyingDutchman CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create uploads dir
      run: |
        sudo mkdir -p /home/sanpc/uploads/
        sudo chown -R $USER:$USER /home/sanpc/uploads/
        sudo chmod -R 755 /home/sanpc/uploads/

    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B verify -X -e

    - name: Generate coverage report
      run: mvn jacoco:report

    - name: Upload Jacoco reports
      uses: actions/upload-artifact@v4.3.6
      with:
        name: test-reports
        path: target/site

    - name: Docker login
      uses: docker/login-action@v3.3.0
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker build and push
      uses: docker/build-push-action@v6.7.0
      with: 
        context: .
        file: Dockerfile
        push: true
        tags: fedec/flyingdutchman:latest

    - name: Docker build and push database
      uses: docker/build-push-action@v6.7.0
      with: 
        context: . 
        file: DockerfileSQL
        push: true
        tags: fedec/flyingdutchman_db:latest

  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Pull latest images
      run: docker compose pull

    - name: Build docker compose
      run: docker compose build --no-cache
    
    - name: Up docker
      run: docker compose up -d --force-recreate

    - name: Check docker logs
      run: docker logs flyingdutchman

    - name: Download Jacoco report
      uses: actions/download-artifact@v4.1.8
      with:
        name: test-reports
        path: reports