name: FlyingDutchman CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read 

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify

    - name: Generate coverage report
      run: mvn jacoco:report

    - name: Upload Jacoco reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/site

    - name: Docker login
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker build and push
      uses: docker/build-push-action@v5
      with: 
        context: .
        file: Dockerfile
        push: true 
        tags: fedec/flyingdutchman:latest

    - name: Docker build and push database
      uses: docker/build-push-action@v5
      with: 
        context: . 
        file: DockerSQL
        push: true
        tags: fedec/flyingdutchman_db:latest

  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build docker compose
      run: docker-compose build
    
    - name: Up docker
      run: docker-compose up -d

    - name: Download Jacoco report
      uses: actions/download-artifact@v4
      with:
        name: test-reports
        path: flyingdutchman/reports
