name: Test Runner

on: [push]

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print runner information
        run: echo "Runner is working!"
